spring:
  application:
    name: project_java_springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_java_springboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    com.guicr3: DEBUG
